Repository Runnect/Runnect-Spring-Boot-Server, pull requests merged in 2023-11, with the labels that each got.

#64 [Feat] createPublicCourse
  src/main/java/org/runnect/server/auth/controller/AuthController.java
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/common/exception/ConflictException.java
  src/main/java/org/runnect/server/course/entity/Course.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/request/CreatePublicCourseRequestDto.java
  src/main/java/org/runnect/server/publicCourse/dto/response/CreatePublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, feat

#66 [Feat] getStampByUser
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/user/controller/UserController.java
  src/main/java/org/runnect/server/user/controller/UserStampController.java
  src/main/java/org/runnect/server/user/dto/response/GetUserStampsResponseDto.java
  src/main/java/org/runnect/server/user/repository/UserRepository.java
  src/main/java/org/runnect/server/user/service/UserStampService.java
Labels: sunny, feat

#68 [Feat] deleteCourse
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/dto/request/DeleteCoursesRequestDto.java
  src/main/java/org/runnect/server/course/dto/response/DeleteCoursesResponseDto.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny, feat

#69 [Feat] getPublicCourseByUser
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/course/entity/Course.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getPublicCourseByUser/GetPublicCourseByUserPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getPublicCourseByUser/GetPublicCourseByUserResponseDto.java
  src/main/java/org/runnect/server/publicCourse/entity/PublicCourse.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/scrap/repository/ScrapRepository.java
Labels: suhwa, feat

#74 [Fix] @UserId
  src/main/java/org/runnect/server/auth/controller/AuthController.java
  src/main/java/org/runnect/server/common/resolver/userId/UserIdResolver.java
Labels: suhwa, fix

#77 [Feat] getPublicCourseDetail
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/response/GetPublicCourseDetailResponseDto.java
  src/main/java/org/runnect/server/publicCourse/repository/PublicCourseRepository.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/scrap/repository/ScrapRepository.java
Labels: suhwa, feat

#87 [Feat] searchPublicCourse
  src/main/java/org/runnect/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
  src/main/java/org/runnect/server/common/constant/SortStatus.java
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/common/resolver/WebConfig.java
  src/main/java/org/runnect/server/common/resolver/sort/SortStatusId.java
  src/main/java/org/runnect/server/common/resolver/sort/SortStatusIdResolver.java
  src/main/java/org/runnect/server/common/resolver/userId/UserIdResolver.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/response/recommendPublicCourse/RecommendPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/recommendPublicCourse/RecommendPublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/dto/response/searchPublicCourse/SearchPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/searchPublicCourse/SearchPublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/entity/PublicCourse.java
  src/main/java/org/runnect/server/publicCourse/repository/PublicCourseRepository.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/record/controller/RecordController.java
Labels: suhwa, feat

#82 [Feat] getPublicCourseTotalPageCount
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/response/GetPublicCourseTotalPageCountResponseDto.java
  src/main/java/org/runnect/server/publicCourse/repository/PublicCourseRepository.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, feat

#84 [Fix] deletePublicCourse,deleteCourse
  src/main/java/org/runnect/server/course/entity/Course.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/course/service/CourseService.java
  src/main/java/org/runnect/server/publicCourse/entity/PublicCourse.java
  src/main/java/org/runnect/server/publicCourse/repository/PublicCourseRepository.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/record/entity/Record.java
  src/main/java/org/runnect/server/scrap/entity/Scrap.java
  src/main/java/org/runnect/server/user/entity/RunnectUser.java
  src/main/java/org/runnect/server/user/entity/UserStamp.java
  src/main/java/org/runnect/server/user/service/UserService.java
Labels: suhwa, fix

#89 [Feat] getMarathonPublicCourse
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getMarathonPublicCourse/GetMarathonPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getMarathonPublicCourse/GetMarathonPublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, feat

#91 [Feat] deletUser
  src/main/java/org/runnect/server/auth/service/AppleSignInService.java
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/user/controller/UserController.java
  src/main/java/org/runnect/server/user/dto/response/DeleteUserResponseDto.java
  src/main/java/org/runnect/server/user/repository/UserRepository.java
  src/main/java/org/runnect/server/user/service/UserService.java
Labels: suhwa, feat

#76 [Fix] fetch 사용하는 jpa 함수 이슈
  src/main/java/org/runnect/server/course/dto/response/GetCourseDetailResponseDto.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/course/service/CourseService.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: sunny, fix

#102 [Feat] @UserId 사용
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/record/controller/RecordController.java
  src/main/java/org/runnect/server/scrap/controller/ScrapController.java
  src/main/java/org/runnect/server/user/controller/UserController.java
Labels: sunny, feat

#92 [Feat] nullUserConvert알수없음
  src/main/java/org/runnect/server/common/dto/DepartureResponse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/GetPublicCourseDetailResponseDto.java
  src/main/java/org/runnect/server/publicCourse/dto/response/PublicCourseDepartureResponse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getMarathonPublicCourse/GetMarathonPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/getPublicCourseByUser/GetPublicCourseByUserPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/dto/response/recommendPublicCourse/RecommendPublicCourse.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/user/entity/RunnectUser.java
  src/main/java/org/runnect/server/user/entity/StampType.java
Labels: suhwa, feat

#93 [Feat] visitMode
  src/main/java/org/runnect/server/common/module/check/TypeChecker.java
  src/main/java/org/runnect/server/common/resolver/userId/UserIdResolver.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/user/entity/SocialType.java
Labels: suhwa, feat

#105 [Fix] fetch join을 제거한다.
  src/main/java/org/runnect/server/user/repository/UserRepository.java
Labels: sunny, fix

#109 [Fix] getPublicCourseDetail
  src/main/java/org/runnect/server/publicCourse/dto/response/GetPublicCourseDetailResponseDto.java
Labels: suhwa, fix

#112 [Fix] get public course detail
  src/main/java/org/runnect/server/publicCourse/dto/response/GetPublicCourseDetailResponseDto.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/user/entity/RunnectUser.java
Labels: suhwa, fix
