Repository Runnect/Runnect-Spring-Boot-Server, pull requests merged in 2023-12, with the labels that each got.

#106 [Feat] createKakaoSocialLogin
  src/main/java/org/runnect/server/auth/service/AuthService.java
  src/main/java/org/runnect/server/auth/service/KakaoSignInService.java
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
Labels: surin❤️

#117 [Fix] public course scrap
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, fix

#116 [Fix] recommandPublicCourse
  src/main/java/org/runnect/server/publicCourse/dto/response/recommendPublicCourse/RecommendPublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, fix

#120 [test] course convert 예외 발생시 로그를 남긴다.
  src/main/java/org/runnect/server/common/module/convert/CoordinatePathConverter.java
Labels: sunny

#129 [Feat] 유저 프로필 조회 쿼리문을 수정한다.
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/user/service/UserService.java
Labels: sunny

#131 [Feat] 코스 생성 시 path 값을 List로 받는 v2 controller를 만든다.
  src/main/java/org/runnect/server/common/module/convert/CoordinateDto.java
  src/main/java/org/runnect/server/common/module/convert/CoordinatePathConverter.java
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/dto/request/CourseCreateRequestDtoV2.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny

#133 [Fix] 유저 프로필에서 scrap 정보를 올바르게 가져온다.
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/scrap/repository/ScrapRepository.java
  src/main/java/org/runnect/server/user/service/UserService.java
Labels: sunny

#135 [Fix] createAndDeleteScrap시 스크랩 전체 개수도 반환
  src/main/java/org/runnect/server/scrap/controller/ScrapController.java
  src/main/java/org/runnect/server/scrap/dto/response/CreateAndDeleteScrapResponseDto.java
  src/main/java/org/runnect/server/scrap/service/ScrapService.java
Labels: surin❤️, fix

#137 [Fix] getPublicCourseDetail
  src/main/java/org/runnect/server/publicCourse/entity/PublicCourse.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: suhwa, fix

#139 [Fix] 코스 생성 API를 v2로 통일
  src/main/java/org/runnect/server/common/module/convert/CoordinatePathConverter.java
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/dto/request/CourseCreateRequestDto.java
  src/main/java/org/runnect/server/course/dto/request/CourseCreateRequestDtoV2.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny

#141 [Feat] 내가 그린 코스 조회 시 distance도 함께 반환
  src/main/java/org/runnect/server/course/dto/response/CourseResponse.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny
