Repository Runnect/Runnect-Spring-Boot-Server, pull requests merged in 2023-10, with the labels that each got.

#48 [Feat] 코스 생성 시 title도 함께 추가
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/dto/request/CourseCreateRequestDto.java
  src/main/java/org/runnect/server/course/dto/response/CourseResponse.java
  src/main/java/org/runnect/server/course/dto/response/GetCourseDetailResponseDto.java
  src/main/java/org/runnect/server/course/entity/Course.java
  src/main/java/org/runnect/server/course/repository/CourseRepository.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny

#51 [Feat] updatePublicCourse
  src/main/java/org/runnect/server/common/exception/ErrorStatus.java
  src/main/java/org/runnect/server/common/exception/SuccessStatus.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/dto/request/UpdatePublicCourseRequestDto.java
  src/main/java/org/runnect/server/publicCourse/dto/response/UpdatePublicCourseResponseDto.java
  src/main/java/org/runnect/server/publicCourse/entity/PublicCourse.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
Labels: surin❤️

#52 [Feat] Google 소셜 로그인
  build.gradle
  src/main/java/org/runnect/server/auth/controller/AuthController.java
  src/main/java/org/runnect/server/auth/dto/request/SignInRequestDto.java
  src/main/java/org/runnect/server/auth/dto/response/SignInResponseDto.java
  src/main/java/org/runnect/server/auth/dto/response/SocialInfoResponseDto.java
  src/main/java/org/runnect/server/auth/service/AuthService.java
  src/main/java/org/runnect/server/auth/service/GoogleSignInService.java
  src/main/java/org/runnect/server/common/exception/ErrorStatus.java
  src/main/java/org/runnect/server/common/exception/UnauthorizedException.java
  src/main/java/org/runnect/server/common/module/convert/NicknameGenerator.java
  src/main/java/org/runnect/server/config/RedisConfig.java
  src/main/java/org/runnect/server/config/jwt/JwtService.java
  src/main/java/org/runnect/server/user/entity/RunnectUser.java
  src/main/java/org/runnect/server/user/repository/UserRepository.java
Labels: sunny

#62 [Feat] get new token
  src/main/java/org/runnect/server/auth/controller/AuthController.java
  src/main/java/org/runnect/server/auth/dto/response/GetNewTokenResponseDto.java
  src/main/java/org/runnect/server/auth/service/AuthService.java
  src/main/java/org/runnect/server/auth/service/GoogleSignInService.java
  src/main/java/org/runnect/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/runnect/server/common/constant/ErrorStatus.java
  src/main/java/org/runnect/server/common/constant/SuccessStatus.java
  src/main/java/org/runnect/server/common/constant/TokenStatus.java
  src/main/java/org/runnect/server/common/dto/ApiResponseDto.java
  src/main/java/org/runnect/server/common/exception/BadRequestException.java
  src/main/java/org/runnect/server/common/exception/BasicException.java
  src/main/java/org/runnect/server/common/exception/NotFoundException.java
  src/main/java/org/runnect/server/common/exception/PermissionDeniedException.java
  src/main/java/org/runnect/server/common/exception/UnauthorizedException.java
  src/main/java/org/runnect/server/common/module/convert/CoordinatePathConverter.java
  src/main/java/org/runnect/server/common/resolver/userId/UserIdResolver.java
  src/main/java/org/runnect/server/config/jwt/JwtService.java
  src/main/java/org/runnect/server/config/redis/RedisConfig.java
  src/main/java/org/runnect/server/config/redis/RedisService.java
  src/main/java/org/runnect/server/course/controller/CourseController.java
  src/main/java/org/runnect/server/course/service/CourseService.java
  src/main/java/org/runnect/server/external/aws/S3Service.java
  src/main/java/org/runnect/server/publicCourse/controller/PublicCourseController.java
  src/main/java/org/runnect/server/publicCourse/service/PublicCourseService.java
  src/main/java/org/runnect/server/record/controller/RecordController.java
  src/main/java/org/runnect/server/record/service/RecordService.java
  src/main/java/org/runnect/server/scrap/controller/ScrapController.java
  src/main/java/org/runnect/server/scrap/service/ScrapService.java
  src/main/java/org/runnect/server/user/controller/UserController.java
  src/main/java/org/runnect/server/user/exception/authException/InvalidAccessTokenException.java
  src/main/java/org/runnect/server/user/exception/authException/InvalidRefreshTokenException.java
  src/main/java/org/runnect/server/user/exception/authException/NullAccessTokenException.java
  src/main/java/org/runnect/server/user/exception/authException/TimeExpiredAccessTokenException.java
  src/main/java/org/runnect/server/user/exception/authException/TimeExpiredRefreshTokenException.java
  src/main/java/org/runnect/server/user/exception/userException/DuplicateNicknameException.java
  src/main/java/org/runnect/server/user/exception/userException/NotFoundUserException.java
  src/main/java/org/runnect/server/user/service/UserService.java
Labels: suhwa, feat

#56 [Fix] createCourse requestDTO 변경
  src/main/java/org/runnect/server/course/dto/request/CourseCreateRequestDto.java
Labels: sunny

#57 [Feat] path 타입 text -> postGis으로 변경
  build.gradle
  src/main/java/org/runnect/server/common/module/convert/CoordinatePathConverter.java
  src/main/java/org/runnect/server/course/entity/Course.java
  src/main/java/org/runnect/server/course/service/CourseService.java
Labels: sunny
